[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "lumache"
authors = [{name = "caict", email = "guoshijie@caict.ac.cn"}]
dynamic = ["version", "description"]
